# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hlctl < Formula
  desc "CLI for managing homelab infrastructure"
  homepage "https://github.com/bwilczynski/homelab-cli"
  version "20260508.87ac"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/bwilczynski/homelab-cli/releases/download/v20260508.87ac/hlctl_20260508.87ac_darwin_amd64.tar.gz"
    sha256 "13bbcae12a5bb6bf0a37cf2b8a61bcf563a0899e5bec0ae29412378f9b201130"

    define_method(:install) do
      bin.install "hlctl"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/bwilczynski/homelab-cli/releases/download/v20260508.87ac/hlctl_20260508.87ac_darwin_arm64.tar.gz"
    sha256 "02594f1fe06a83185cd25e104b96706da2480ff3bd8e217748ca084d9a345fdc"

    define_method(:install) do
      bin.install "hlctl"
    end
  end

  test do
    system "#{bin}/hlctl", "--version"
  end
end
