# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hlctl < Formula
  desc "CLI for managing homelab infrastructure"
  homepage "https://github.com/bwilczynski/homelab-cli"
  version "20260530.e08a"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/bwilczynski/homelab-cli/releases/download/v20260530.e08a/hlctl_20260530.e08a_darwin_amd64.tar.gz"
    sha256 "8cb5f06038b8192fcc61e7cdee030e720bf47c2c1bb36f2e15eef0cf063d47ce"

    define_method(:install) do
      bin.install "hlctl"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/bwilczynski/homelab-cli/releases/download/v20260530.e08a/hlctl_20260530.e08a_darwin_arm64.tar.gz"
    sha256 "9c2f545e49dcaf30e50cbb314d70e45cf6e2c0bfa4e018ae259c5f07098dacdf"

    define_method(:install) do
      bin.install "hlctl"
    end
  end

  test do
    system "#{bin}/hlctl", "--version"
  end
end
