# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hlctl < Formula
  desc "CLI for managing homelab infrastructure"
  homepage "https://github.com/bwilczynski/homelab-cli"
  version "20260517.b3d1"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/bwilczynski/homelab-cli/releases/download/v20260517.b3d1/hlctl_20260517.b3d1_darwin_amd64.tar.gz"
    sha256 "a9962ad24b842d8f4e87403de93f74497c82a682195f3f529a35e8bea9d891d4"

    define_method(:install) do
      bin.install "hlctl"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/bwilczynski/homelab-cli/releases/download/v20260517.b3d1/hlctl_20260517.b3d1_darwin_arm64.tar.gz"
    sha256 "357e59c22835849efd2e94fe0a8d04d5de442f65c9efd9497bd6c54604cbaf90"

    define_method(:install) do
      bin.install "hlctl"
    end
  end

  test do
    system "#{bin}/hlctl", "--version"
  end
end
