# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hlctl < Formula
  desc "CLI for managing homelab infrastructure"
  homepage "https://github.com/bwilczynski/homelab-cli"
  version "20260518.0d1e"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/bwilczynski/homelab-cli/releases/download/v20260518.0d1e/hlctl_20260518.0d1e_darwin_amd64.tar.gz"
    sha256 "50b5b3d30608f8aff84048d779b76aeffc3923a6a5e41a02413042be8268c12f"

    define_method(:install) do
      bin.install "hlctl"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/bwilczynski/homelab-cli/releases/download/v20260518.0d1e/hlctl_20260518.0d1e_darwin_arm64.tar.gz"
    sha256 "e7953d5c20531472b7715befbf9abbc27d41298422f1c9c07f80743188717c74"

    define_method(:install) do
      bin.install "hlctl"
    end
  end

  test do
    system "#{bin}/hlctl", "--version"
  end
end
